run:
  tests: true

linters-settings:
  gofmt:
    simplify: true

  gci:
    sections:
    - standard
    - default
    - prefix(github.com/tsuru/rpaas-operator)

linters:
  enable:
  - goimports
  - gofmt
  - misspell
  - govet
  - gci
  disable:
  - errcheck
