FROM golang:1.20-alpine3.18 AS builder
COPY . /go/src/github.com/tsuru/rpaas-operator
WORKDIR /go/src/github.com/tsuru/rpaas-operator
RUN apk add --update gcc git make musl-dev && \
    make build/purger

FROM alpine:3.18
COPY --from=builder /go/src/github.com/tsuru/rpaas-operator/bin/purger /bin/rpaas-purger
RUN apk update && \
    apk add --no-cache ca-certificates && \
    rm /var/cache/apk/*
EXPOSE 9990
CMD ["/bin/rpaas-purger"]
