# permissions for end users to edit rpaasallowedupstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpaasallowedupstreams-editor-role
rules:
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasallowedupstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasallowedupstreams/status
  verbs:
  - get
