apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rpaasplans.extensions.tsuru.io
spec:
  group: extensions.tsuru.io
  names:
    kind: RpaasPlan
    listKind: RpaasPlanList
    plural: rpaasplans
    singular: rpaasplan
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
