apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rpaas-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - extensions.tsuru.io
  resources:
  - rpaasinstances
  - rpaasplans
  - rpaasflavors
  - rpaasportallocations
  verbs:
  - '*'
- apiGroups:
  - nginx.tsuru.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpaas-cache-syncer
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rpaas-session-tickets-rotator
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - patch
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
