# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/extensions.tsuru.io_rpaasinstances.yaml
- bases/extensions.tsuru.io_rpaasvalidations.yaml
- bases/extensions.tsuru.io_rpaasplans.yaml
- bases/extensions.tsuru.io_rpaasflavors.yaml
# +kubebuilder:scaffold:crdkustomizeresource
