// Copyright 2019 tsuru authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package cmd

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/olekukonko/tablewriter"
	"github.com/urfave/cli/v2"

	"github.com/tsuru/rpaas-operator/pkg/rpaas/client/autogenerated"
)

func NewCmdAutoscale() *cli.Command {
	return &cli.Command{
		Name:  "autoscale",
		Usage: "Manages autoscaling settings of an instance",
		Subcommands: []*cli.Command{
			NewCmdGetAutoscale(),
			NewCmdUpdateAutoscale(),
			NewCmdRemoveAutoscale(),
		},
	}
}

func NewCmdUpdateAutoscale() *cli.Command {
	return &cli.Command{
		Name:    "add",
		Aliases: []string{"update"},
		Usage:   "Updates the autoscaling parameters and targets of an reverse proxy instance",
		Description: `
# Scale up/down based on 75% of CPU utilization over all pods:
rpaasv2 autoscale update -s my-instance -i my-instance --min 2 --max 20 --cpu 75

# Scale up/down based on avg 100 HTTP requests per second:
rpaasv2 autoscale update -s my-service -i my-instance --min 2 --max 20 --rps 100

# Combine the two targets above together:
rpaasv2 autoscale update -s my-service -i my-instance --min 2 --max 20 --cpu 75 --rps 100

# Set a scheduled window to scale up at least one replica every weekday from 8 AM until 8 PM.
rpaasv2 autoscale update -s my-service -i my-instance \
	--min 0 --max 20 \
	--schedule '{"minReplicas": 1, "start": "00 08 * * 1-5", "end": "00 20 * * 1-5"}'

# Set two scheduled windows:
#	1) to scale up to max replicas every Tueday from 8 PM until at 0 PM (Wednesday)
#	2) to scale up to max replicas every Sunday all day
rpaasv2 autoscale update -s my-service -i my-instance \
	--min 2 --max 10 \
	--schedule '{"minReplicas": 10, "start": "00 20 * * 2", "end": "00 00 * * 3"}' \
	--schedule '{"minReplicas": 10, "start": "00 00 * * 0", "end": "59 23 * * 0"}'
`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "service",
				Aliases: []string{"tsuru-service", "s"},
				Usage:   "the Tsuru service name",
			},
			&cli.StringFlag{
				Name:     "instance",
				Aliases:  []string{"tsuru-service-instance", "i"},
				Usage:    "the reverse proxy instance name",
				Required: true,
			},
			&cli.IntFlag{
				Name:     "min",
				Usage:    "the lower limit of replicas that can be reached",
				Required: false,
			},
			&cli.IntFlag{
				Name:     "max",
				Usage:    "the upper limit of replicas that can be reached",
				Required: true,
			},
			&cli.IntFlag{
				Name:        "cpu",
				Aliases:     []string{"cpu-utilization"},
				Usage:       "the target average CPU utilization on all replicas (in percentage format, e.g. 80 equals to 80%)",
				DefaultText: "N/A",
			},
			&cli.IntFlag{
				Name:        "memory",
				Aliases:     []string{"memory-utilization"},
				Usage:       "the target average memory utilization on all the replicas (in percentage format, e.g. 80 equals to 80%)",
				DefaultText: "N/A",
			},
			&cli.IntFlag{
				Name:        "rps",
				Aliases:     []string{"requests-per-second"},
				Usage:       "the target average of HTTP requests per seconds between replicas (e.g. 100, means 100 req/s)",
				DefaultText: "N/A",
			},
			&cli.StringSliceFlag{
				Name:    "schedule",
				Aliases: []string{"scheduled-window"},
				Usage:   "the time-window where the instance can scale in/out regardless of traffic or resource utilization",
			},
		},
		Action: runUpdateAutoscale,
	}
}

func runUpdateAutoscale(c *cli.Context) error {
	var schedules []autogenerated.ScheduledWindow
	for _, s := range c.StringSlice("schedule") {
		var sw autogenerated.ScheduledWindow
		if err := json.Unmarshal([]byte(s), &sw); err != nil {
			return err
		}

		schedules = append(schedules, sw)
	}

	autoscale := autogenerated.Autoscale{
		MinReplicas: int32(c.Int("min")),
		MaxReplicas: int32(c.Int("max")),
		Cpu:         autogenerated.PtrInt32(int32(c.Int("cpu"))),
		Memory:      autogenerated.PtrInt32(int32(c.Int("memory"))),
		Rps:         autogenerated.PtrInt32(int32(c.Int("rps"))),
		Schedules:   schedules,
	}

	_, err := NewAutogeneratedClient(c).RpaasApi.UpdateAutoscale(c.Context, c.String("instance")).Autoscale(autoscale).Execute()
	if err != nil {
		return fmt.Errorf("could not update the autoscale on RPaaS API: %w", err)
	}

	fmt.Fprintf(c.App.Writer, "Autoscale of %s successfully updated!\n", formatInstanceName(c))
	return nil
}

func NewCmdGetAutoscale() *cli.Command {
	return &cli.Command{
		Name:  "info",
		Usage: "Shows  the autoscaling settings",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "service",
				Aliases: []string{"tsuru-service", "s"},
				Usage:   "the Tsuru service name",
			},
			&cli.StringFlag{
				Name:     "instance",
				Aliases:  []string{"tsuru-service-instance", "i"},
				Usage:    "the reverse proxy instance name",
				Required: true,
			},
			&cli.BoolFlag{
				Name:  "json",
				Usage: "show as JSON instead of go template format",
				Value: false,
			},
		},
		Action: runGetAutoscale,
	}
}

func runGetAutoscale(c *cli.Context) error {
	autoscale, _, err := NewAutogeneratedClient(c).RpaasApi.GetAutoscale(c.Context, c.String("instance")).Execute()
	if err != nil {
		return fmt.Errorf("could not get autoscale from RPaaS API: %w", err)
	}

	if outputAsJSON := c.Bool("json"); outputAsJSON {
		return writeJSON(c.App.Writer, autoscale)
	}

	writeAutoscale(c.App.Writer, autoscale)
	return nil
}

func NewCmdRemoveAutoscale() *cli.Command {
	return &cli.Command{
		Name:    "remove",
		Usage:   "Removes the autoscaling parameters of instance",
		Aliases: []string{"delete"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "service",
				Aliases: []string{"tsuru-service", "s"},
				Usage:   "the Tsuru service name",
			},
			&cli.StringFlag{
				Name:     "instance",
				Aliases:  []string{"tsuru-service-instance", "i"},
				Usage:    "the reverse proxy instance name",
				Required: true,
			},
		},
		Action: runRemoveAutoscale,
	}
}

func runRemoveAutoscale(c *cli.Context) error {
	_, err := NewAutogeneratedClient(c).RpaasApi.RemoveAutoscale(c.Context, c.String("instance")).Execute()
	if err != nil {
		return fmt.Errorf("could not delete the autoscale on RPaaS API: %w", err)
	}

	fmt.Fprintf(c.App.Writer, "Autoscale of %s successfully removed\n", formatInstanceName(c))
	return nil
}

func writeAutoscale(w io.Writer, autoscale *autogenerated.Autoscale) {
	if autoscale == nil {
		return
	}

	table := tablewriter.NewWriter(w)
	table.SetHeader([]string{"Min replicas", "Max replicas", "CPU target (%)", "Memory target (%)", "RPS target (req/s)", "Schedule(s)"})
	table.SetAutoFormatHeaders(false)
	table.SetHeaderAlignment(tablewriter.ALIGN_CENTER)
	table.SetAutoWrapText(false)
	table.SetRowLine(false)

	table.SetColumnAlignment([]int{
		tablewriter.ALIGN_CENTER,
		tablewriter.ALIGN_CENTER,
		tablewriter.ALIGN_CENTER,
		tablewriter.ALIGN_CENTER,
		tablewriter.ALIGN_CENTER,
		tablewriter.ALIGN_LEFT,
	})

	min := strconv.Itoa(int(autoscale.MinReplicas))
	max := strconv.Itoa(int(autoscale.MaxReplicas))

	cpu := "N/A"
	if autoscale.Cpu != nil {
		cpu = strconv.Itoa(int(*autoscale.Cpu))
	}

	mem := "N/A"
	if autoscale.Memory != nil {
		mem = strconv.Itoa(int(*autoscale.Memory))
	}

	rps := "N/A"
	if autoscale.Rps != nil {
		rps = strconv.Itoa(int(*autoscale.Rps))
	}

	var schedules strings.Builder
	if len(autoscale.Schedules) == 0 {
		fmt.Fprint(&schedules, "N/A")
	}

	for i, s := range autoscale.Schedules {
		if i > 0 {
			fmt.Fprintln(&schedules)
			fmt.Fprintln(&schedules)
		}

		fmt.Fprintf(&schedules, "Window %d:\n", i+1)
		fmt.Fprintln(&schedules, "  Min replicas:", s.MinReplicas)
		fmt.Fprintf(&schedules, "  Start: %q\n", s.Start)
		fmt.Fprintf(&schedules, "  End:   %q", s.End)
	}

	table.Append([]string{min, max, cpu, mem, rps, schedules.String()})
	table.Render()
}

func writeJSON(w io.Writer, v any) error {
	e := json.NewEncoder(w)
	e.SetIndent("", "\t")
	return e.Encode(v)
}
