/*
Reverse Proxy as a Service

The presented API definition (formally called as RPaaS v2 API) is a superset of [Tsuru Service API] and the [legacy RPaaS][RPaaS v1 API] (aka RPaaS v1).  Source code: [github.com/tsuru/rpaas-operator](https://github.com/tsuru/rpaas-operator.git)  [Tsuru Service API]: https://app.swaggerhub.com/apis/tsuru/tsuru-service_api [RPaaS v1 API]: https://raw.githubusercontent.com/tsuru/rpaas/master/rpaas/api.py

API version: v2
Contact: tsuru@g.globo
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogenerated

import (
	"encoding/json"
)

// checks if the PlanSchemasServiceBinding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanSchemasServiceBinding{}

// PlanSchemasServiceBinding struct for PlanSchemasServiceBinding
type PlanSchemasServiceBinding struct {
	Create *PlanSchemasServiceBindingCreate `json:"create,omitempty"`
}

// NewPlanSchemasServiceBinding instantiates a new PlanSchemasServiceBinding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanSchemasServiceBinding() *PlanSchemasServiceBinding {
	this := PlanSchemasServiceBinding{}
	return &this
}

// NewPlanSchemasServiceBindingWithDefaults instantiates a new PlanSchemasServiceBinding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanSchemasServiceBindingWithDefaults() *PlanSchemasServiceBinding {
	this := PlanSchemasServiceBinding{}
	return &this
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *PlanSchemasServiceBinding) GetCreate() PlanSchemasServiceBindingCreate {
	if o == nil || IsNil(o.Create) {
		var ret PlanSchemasServiceBindingCreate
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanSchemasServiceBinding) GetCreateOk() (*PlanSchemasServiceBindingCreate, bool) {
	if o == nil || IsNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *PlanSchemasServiceBinding) HasCreate() bool {
	if o != nil && !IsNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given PlanSchemasServiceBindingCreate and assigns it to the Create field.
func (o *PlanSchemasServiceBinding) SetCreate(v PlanSchemasServiceBindingCreate) {
	o.Create = &v
}

func (o PlanSchemasServiceBinding) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanSchemasServiceBinding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Create) {
		toSerialize["create"] = o.Create
	}
	return toSerialize, nil
}

type NullablePlanSchemasServiceBinding struct {
	value *PlanSchemasServiceBinding
	isSet bool
}

func (v NullablePlanSchemasServiceBinding) Get() *PlanSchemasServiceBinding {
	return v.value
}

func (v *NullablePlanSchemasServiceBinding) Set(val *PlanSchemasServiceBinding) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanSchemasServiceBinding) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanSchemasServiceBinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanSchemasServiceBinding(val *PlanSchemasServiceBinding) *NullablePlanSchemasServiceBinding {
	return &NullablePlanSchemasServiceBinding{value: val, isSet: true}
}

func (v NullablePlanSchemasServiceBinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanSchemasServiceBinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
