/*
Reverse Proxy as a Service

The presented API definition (formally called as RPaaS v2 API) is a superset of [Tsuru Service API] and the [legacy RPaaS][RPaaS v1 API] (aka RPaaS v1).  Source code: [github.com/tsuru/rpaas-operator](https://github.com/tsuru/rpaas-operator.git)  [Tsuru Service API]: https://app.swaggerhub.com/apis/tsuru/tsuru-service_api [RPaaS v1 API]: https://raw.githubusercontent.com/tsuru/rpaas/master/rpaas/api.py

API version: v2
Contact: tsuru@g.globo
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogenerated

import (
	"encoding/json"
)

// checks if the ScaleDown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScaleDown{}

// ScaleDown struct for ScaleDown
type ScaleDown struct {
	// is the number of seconds for which past recommendations should be considered while scaling up or scaling down.
	StabilizationWindowSeconds *int32 `json:"stabilizationWindowSeconds,omitempty"`
	// set a policy with (value: unitsPolicyValue, type: Pods, periodSeconds: 60s)
	UnitsPolicyValue *int32 `json:"unitsPolicyValue,omitempty"`
	// set a policy with (value: percentPolicyValue, type: Percent, periodSeconds: 60s)
	PercentPolicyValue *int32 `json:"percentPolicyValue,omitempty"`
}

// NewScaleDown instantiates a new ScaleDown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScaleDown() *ScaleDown {
	this := ScaleDown{}
	return &this
}

// NewScaleDownWithDefaults instantiates a new ScaleDown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScaleDownWithDefaults() *ScaleDown {
	this := ScaleDown{}
	return &this
}

// GetStabilizationWindowSeconds returns the StabilizationWindowSeconds field value if set, zero value otherwise.
func (o *ScaleDown) GetStabilizationWindowSeconds() int32 {
	if o == nil || IsNil(o.StabilizationWindowSeconds) {
		var ret int32
		return ret
	}
	return *o.StabilizationWindowSeconds
}

// GetStabilizationWindowSecondsOk returns a tuple with the StabilizationWindowSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScaleDown) GetStabilizationWindowSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.StabilizationWindowSeconds) {
		return nil, false
	}
	return o.StabilizationWindowSeconds, true
}

// HasStabilizationWindowSeconds returns a boolean if a field has been set.
func (o *ScaleDown) HasStabilizationWindowSeconds() bool {
	if o != nil && !IsNil(o.StabilizationWindowSeconds) {
		return true
	}

	return false
}

// SetStabilizationWindowSeconds gets a reference to the given int32 and assigns it to the StabilizationWindowSeconds field.
func (o *ScaleDown) SetStabilizationWindowSeconds(v int32) {
	o.StabilizationWindowSeconds = &v
}

// GetUnitsPolicyValue returns the UnitsPolicyValue field value if set, zero value otherwise.
func (o *ScaleDown) GetUnitsPolicyValue() int32 {
	if o == nil || IsNil(o.UnitsPolicyValue) {
		var ret int32
		return ret
	}
	return *o.UnitsPolicyValue
}

// GetUnitsPolicyValueOk returns a tuple with the UnitsPolicyValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScaleDown) GetUnitsPolicyValueOk() (*int32, bool) {
	if o == nil || IsNil(o.UnitsPolicyValue) {
		return nil, false
	}
	return o.UnitsPolicyValue, true
}

// HasUnitsPolicyValue returns a boolean if a field has been set.
func (o *ScaleDown) HasUnitsPolicyValue() bool {
	if o != nil && !IsNil(o.UnitsPolicyValue) {
		return true
	}

	return false
}

// SetUnitsPolicyValue gets a reference to the given int32 and assigns it to the UnitsPolicyValue field.
func (o *ScaleDown) SetUnitsPolicyValue(v int32) {
	o.UnitsPolicyValue = &v
}

// GetPercentPolicyValue returns the PercentPolicyValue field value if set, zero value otherwise.
func (o *ScaleDown) GetPercentPolicyValue() int32 {
	if o == nil || IsNil(o.PercentPolicyValue) {
		var ret int32
		return ret
	}
	return *o.PercentPolicyValue
}

// GetPercentPolicyValueOk returns a tuple with the PercentPolicyValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScaleDown) GetPercentPolicyValueOk() (*int32, bool) {
	if o == nil || IsNil(o.PercentPolicyValue) {
		return nil, false
	}
	return o.PercentPolicyValue, true
}

// HasPercentPolicyValue returns a boolean if a field has been set.
func (o *ScaleDown) HasPercentPolicyValue() bool {
	if o != nil && !IsNil(o.PercentPolicyValue) {
		return true
	}

	return false
}

// SetPercentPolicyValue gets a reference to the given int32 and assigns it to the PercentPolicyValue field.
func (o *ScaleDown) SetPercentPolicyValue(v int32) {
	o.PercentPolicyValue = &v
}

func (o ScaleDown) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScaleDown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StabilizationWindowSeconds) {
		toSerialize["stabilizationWindowSeconds"] = o.StabilizationWindowSeconds
	}
	if !IsNil(o.UnitsPolicyValue) {
		toSerialize["unitsPolicyValue"] = o.UnitsPolicyValue
	}
	if !IsNil(o.PercentPolicyValue) {
		toSerialize["percentPolicyValue"] = o.PercentPolicyValue
	}
	return toSerialize, nil
}

type NullableScaleDown struct {
	value *ScaleDown
	isSet bool
}

func (v NullableScaleDown) Get() *ScaleDown {
	return v.value
}

func (v *NullableScaleDown) Set(val *ScaleDown) {
	v.value = val
	v.isSet = true
}

func (v NullableScaleDown) IsSet() bool {
	return v.isSet
}

func (v *NullableScaleDown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScaleDown(val *ScaleDown) *NullableScaleDown {
	return &NullableScaleDown{value: val, isSet: true}
}

func (v NullableScaleDown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScaleDown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
