/*
Reverse Proxy as a Service

The presented API definition (formally called as RPaaS v2 API) is a superset of [Tsuru Service API] and the [legacy RPaaS][RPaaS v1 API] (aka RPaaS v1).  Source code: [github.com/tsuru/rpaas-operator](https://github.com/tsuru/rpaas-operator.git)  [Tsuru Service API]: https://app.swaggerhub.com/apis/tsuru/tsuru-service_api [RPaaS v1 API]: https://raw.githubusercontent.com/tsuru/rpaas/master/rpaas/api.py

API version: v2
Contact: tsuru@g.globo
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autogenerated

import (
	"encoding/json"
)

// checks if the Behavior type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Behavior{}

// Behavior struct for Behavior
type Behavior struct {
	ScaleDown *ScaleDown `json:"scaleDown,omitempty"`
}

// NewBehavior instantiates a new Behavior object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBehavior() *Behavior {
	this := Behavior{}
	return &this
}

// NewBehaviorWithDefaults instantiates a new Behavior object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBehaviorWithDefaults() *Behavior {
	this := Behavior{}
	return &this
}

// GetScaleDown returns the ScaleDown field value if set, zero value otherwise.
func (o *Behavior) GetScaleDown() ScaleDown {
	if o == nil || IsNil(o.ScaleDown) {
		var ret ScaleDown
		return ret
	}
	return *o.ScaleDown
}

// GetScaleDownOk returns a tuple with the ScaleDown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Behavior) GetScaleDownOk() (*ScaleDown, bool) {
	if o == nil || IsNil(o.ScaleDown) {
		return nil, false
	}
	return o.ScaleDown, true
}

// HasScaleDown returns a boolean if a field has been set.
func (o *Behavior) HasScaleDown() bool {
	if o != nil && !IsNil(o.ScaleDown) {
		return true
	}

	return false
}

// SetScaleDown gets a reference to the given ScaleDown and assigns it to the ScaleDown field.
func (o *Behavior) SetScaleDown(v ScaleDown) {
	o.ScaleDown = &v
}

func (o Behavior) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Behavior) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScaleDown) {
		toSerialize["scaleDown"] = o.ScaleDown
	}
	return toSerialize, nil
}

type NullableBehavior struct {
	value *Behavior
	isSet bool
}

func (v NullableBehavior) Get() *Behavior {
	return v.value
}

func (v *NullableBehavior) Set(val *Behavior) {
	v.value = val
	v.isSet = true
}

func (v NullableBehavior) IsSet() bool {
	return v.isSet
}

func (v *NullableBehavior) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBehavior(val *Behavior) *NullableBehavior {
	return &NullableBehavior{value: val, isSet: true}
}

func (v NullableBehavior) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBehavior) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
